name: Build-Test-Deploy

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 21 * * *'
jobs:
       
       
 
 Jira-issue-create:
    name: Transition Issue Create
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create new issue
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: P1
        issuetype: Task
        summary: |
              Testing will start for ${{ github.repository }}:

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In progress"




 Jira-Issue-done:
    name: Transition Issue Done

    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Transition issue
      id: transition
      uses: atlassian/gajira-transition@master
      with:
        issue: P1-3
        transition: "Done"
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
       issue: P1-3
       comment: Pipeline Success
    
